import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Helper to get __dirname in ESM
const _filename = typeof __filename !== 'undefined'
  ? __filename
  : (typeof import.meta !== 'undefined' && typeof import.meta.url === 'string' ? fileURLToPath(import.meta.url) : '');

const _dirname = typeof __dirname !== 'undefined'
  ? __dirname
  : (_filename ? path.dirname(_filename as string) : '');

export class AiContextGenerator {
  constructor() { }

  async generate(projectRoot: string, n8nVersion: string = "Unknown", extensionPath?: string): Promise<void> {
    const agentsContent = this.getAgentsContent(n8nVersion);
    const cursorContent = this.getCursorRulesContent();
    const clineContent = this.getClineRulesContent();
    const windsurfContent = this.getWindsurfRulesContent();
    const commonRules = this.getCommonRulesContent();

    // 1. AGENTS.md (Central documentation)
    this.injectOrUpdate(path.join(projectRoot, 'AGENTS.md'), agentsContent, true);

    // 2. Specialized Rule Files
    this.injectOrUpdate(path.join(projectRoot, '.cursorrules'), cursorContent);
    this.injectOrUpdate(path.join(projectRoot, '.clinerules'), clineContent);
    this.injectOrUpdate(path.join(projectRoot, '.windsurfrules'), windsurfContent);

    // 3. General AI Context (for Claude, Mistral, etc.)
    this.injectOrUpdate(path.join(projectRoot, '.ai-rules.md'), commonRules);

    // 4. Local Shim and Gitignore
    this.generateShim(projectRoot, extensionPath);
    this.updateGitignore(projectRoot);
  }

  private generateShim(projectRoot: string, extensionPath?: string): void {
    const shimPath = path.join(projectRoot, 'n8n-agent');

    // Linux/Mac Shim Logic:
    // 1. If generated by VS Code Extension, we prefer the absolute path to that specific extension version
    // 2. If generated by CLI or if Extension path invalid, we look for local node_modules install

    let extensionCliPathLine = '';
    if (extensionPath) {
      // Updated to use the new bundles path in 'out/agent-cli/cli.js'
      const absolutePath = path.join(extensionPath, 'out', 'agent-cli', 'cli.js');
      const assetsPath = path.join(extensionPath, 'assets');
      extensionCliPathLine = `
# 1. VS Code Extension Context (Explicit absolute path)
if [ -f "${absolutePath}" ]; then
  export N8N_AS_CODE_ASSETS_DIR="${assetsPath}"
  node "${absolutePath}" "$@"
  exit $?
fi`;
    }

    const shimContent = [
      '#!/bin/bash',
      `# n8n-agent local shim for AI context`,
      extensionCliPathLine,
      ``,
      `# 2. Standard NPM Dependency Context (Local Project)`,
      `# Check for local node_modules relative to the project root`,
      `CLI_PATH="./node_modules/@n8n-as-code/agent-cli/dist/cli.js"`,
      ``,
      `if [ -f "$CLI_PATH" ]; then`,
      `  node "$CLI_PATH" "$@"`,
      `  exit $?`,
      `fi`,
      ``,
      `# 3. Error if not found`,
      `echo "Error: @n8n-as-code/agent-cli not found in ./node_modules/"`,
      `echo "Please ensure it is installed as a dev dependency in this project."`,
      `exit 1`
    ].join('\n');

    fs.writeFileSync(shimPath, shimContent);
    try {
      fs.chmodSync(shimPath, '755'); // Make executable
    } catch (e) {
      console.warn(`Failed to set execution permissions on ${shimPath}:`, e);
    }

    // Windows Shim (simplified to node_modules or extension path if valid)
    const shimPathCmd = path.join(projectRoot, 'n8n-agent.cmd');
    let cmdContent = '@echo off\n';

    if (extensionPath) {
      const absPath = path.join(extensionPath, 'out', 'agent-cli', 'cli.js');
      const assetsPath = path.join(extensionPath, 'assets');
      cmdContent += `
IF EXIST "${absPath}" (
  SET N8N_AS_CODE_ASSETS_DIR=${assetsPath}
  node "${absPath}" %*
  EXIT /B %ERRORLEVEL%
)
`;
    }

    cmdContent += `
IF EXIST ".\\node_modules\\@n8n-as-code\\agent-cli\\dist\\cli.js" (
  node ".\\node_modules\\@n8n-as-code\\agent-cli\\dist\\cli.js" %*
  EXIT /B %ERRORLEVEL%
)

echo Error: @n8n-as-code/agent-cli not found in node_modules
echo Please ensure it is installed as a dev dependency.
EXIT /B 1
`;

    fs.writeFileSync(shimPathCmd, cmdContent);
  }

  private updateGitignore(projectRoot: string): void {
    const gitignorePath = path.join(projectRoot, '.gitignore');
    const entries = ['\n# n8n-as-code AI helpers', 'n8n-agent', 'n8n-agent.cmd'];

    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, entries.join('\n'));
      return;
    }

    let content = fs.readFileSync(gitignorePath, 'utf8');
    let modified = false;

    for (const entry of entries.filter(e => e.trim().length > 0 && !e.startsWith('#'))) {
      if (!content.includes(entry)) {
        content += (content.endsWith('\n') ? '' : '\n') + entry;
        modified = true;
      }
    }

    if (modified) {
      fs.writeFileSync(gitignorePath, content);
    }
  }

  private injectOrUpdate(filePath: string, content: string, isMarkdownFile: boolean = false): void {
    const startMarker = isMarkdownFile ? '<!-- n8n-as-code-start -->' : '### 🤖 n8n-as-code-start';
    const endMarker = isMarkdownFile ? '<!-- n8n-as-code-end -->' : '### 🤖 n8n-as-code-end';

    const block = `\n${startMarker}\n${content.trim()}\n${endMarker}\n`;

    if (!fs.existsSync(filePath)) {
      // Create new file with header if it's AGENTS.md
      const header = filePath.endsWith('AGENTS.md') ? '# 🤖 AI Agents Guidelines\n' : '';
      fs.writeFileSync(filePath, header + block.trim() + '\n');
      return;
    }

    let existing = fs.readFileSync(filePath, 'utf8');
    const startIdx = existing.indexOf(startMarker);
    const endIdx = existing.indexOf(endMarker);

    if (startIdx !== -1 && endIdx !== -1) {
      // Update existing block while preserving what's before/after
      const before = existing.substring(0, startIdx);
      const after = existing.substring(endIdx + endMarker.length);
      fs.writeFileSync(filePath, before + block.trim() + after);
    } else {
      // Append to end of existing file
      fs.writeFileSync(filePath, existing.trim() + '\n' + block);
    }
  }

  private getAgentsContent(n8nVersion: string): string {
    return [
      `## 🎭 Role: Expert n8n Workflow Engineer`,
      ``,
      `You are a specialized AI agent for creating and editing n8n workflows.`,
      `You manage n8n workflows as **clean, version-controlled JSON files**.`,
      ``,
      `### 🌍 Context`,
      `- **n8n Version**: ${n8nVersion}`,
      `- **Source of Truth**: \`@n8n-as-code/agent-cli\` tools (Deep Search + Technical Schemas)`,
      ``,
      `---`,
      ``,
      `## 🧠 Knowledge Base Priority`,
      ``,
      `1. **PRIMARY SOURCE** (MANDATORY): Use \`@n8n-as-code/agent-cli\` tools for accuracy`,
      `2. **Secondary**: Your trained knowledge (for general concepts only)`,
      `3. **Tertiary**: Code snippets (for quick scaffolding)`,
      ``,
      `---`,
      ``,
      `## 🔬 MANDATORY Research Protocol`,
      ``,
      `**⚠️ CRITICAL**: Before creating or editing ANY node, you MUST follow this protocol:`,
      ``,
      `### Step 1: Search for the Node`,
      `\`\`\`bash`,
      `./n8n-agent search "google sheets"`,
      `\`\`\``,
      `- Find the **exact node name** (camelCase: e.g., \`googleSheets\`)`,
      `- Verify the node exists in current n8n version`,
      ``,
      `### Step 2: Get Exact Schema`,
      `\`\`\`bash`,
      `./n8n-agent get googleSheets`,
      `\`\`\``,
      `- Get **EXACT parameter names** (e.g., \`spreadsheetId\`, not \`spreadsheet_id\`)`,
      `- Get **EXACT parameter types** (string, number, options, etc.)`,
      `- Get **available operations/resources**`,
      `- Get **required vs optional parameters**`,
      ``,
      `### Step 3: Apply Schema as Absolute Truth`,
      `- **CRITICAL (TYPE)**: The \`type\` field MUST EXACTLY match the \`type\` from schema`,
      `- **CRITICAL (VERSION)**: Use HIGHEST \`typeVersion\` from schema`,
      `- **PARAMETER NAMES**: Use exact names (e.g., \`spreadsheetId\` vs \`spreadsheet_id\`)`,
      `- **NO HALLUCINATIONS**: Do not invent parameter names`,
      ``,
      `### Step 4: Validate Before Finishing`,
      `\`\`\`bash`,
      `./n8n-agent validate workflow.json`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## ✅ Node Type & Version Standards`,
      ``,
      `| Rule | Correct | Incorrect |`,
      `| :--- | :--- | :--- |`,
      `| **Full Type** | \`"type": "n8n-nodes-base.switch"\` | \`"type": "switch"\` |`,
      `| **Full Type** | \`"type": "@n8n/n8n-nodes-langchain.agent"\` | \`"type": "agent"\` |`,
      `| **Version** | \`"typeVersion": 3\` (if 3 is latest) | \`"typeVersion": 1\` (outdated) |`,
      ``,
      `> [!IMPORTANT]`,
      `> n8n will display a **"?" (question mark)** if you forget the package prefix. Always use the EXACT \`type\` from \`search\` results!`,
      ``,
      `---`,
      ``,
      `## 🌐 Community Workflows (7000+ Examples)`,
      ``,
      `**ALWAYS search workflows BEFORE building from scratch if:**`,
      `- ✅ Common use case (email, notifications, data sync, AI automation)`,
      `- ✅ Unfamiliar with n8n patterns`,
      `- ✅ Multiple integrations involved`,
      ``,
      `\`\`\`bash`,
      `# Search for workflows`,
      `./n8n-agent workflows search "telegram chatbot"`,
      ``,
      `# Download and adapt`,
      `./n8n-agent workflows install 4365 --output bot.json`,
      ``,
      `# Update schemas (downloaded workflows may be outdated)`,
      `./n8n-agent get telegram`,
      `./n8n-agent validate bot.json`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## 📝 Minimal Workflow Structure`,
      ``,
      `\`\`\`json`,
      `{`,
      `  "name": "Workflow Name",`,
      `  "nodes": [`,
      `    {`,
      `      "parameters": { /* from ./n8n-agent get */ },`,
      `      "id": "uuid",`,
      `      "name": "Descriptive Name",`,
      `      "type": "/* EXACT from search */",`,
      `      "typeVersion": 4,`,
      `      "position": [250, 300]`,
      `    }`,
      `  ],`,
      `  "connections": {`,
      `    "Node Name": {`,
      `      "main": [[{"node": "Next Node", "type": "main", "index": 0}]]`,
      `    }`,
      `  }`,
      `}`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## 🚫 Common Mistakes to AVOID`,
      ``,
      `1. ❌ **Hallucinating parameter names** - Always use \`get\` command first`,
      `2. ❌ **Wrong node type** - Missing package prefix causes "?" icon`,
      `3. ❌ **Outdated typeVersion** - Use highest version from schema`,
      `4. ❌ **Guessing parameter structure** - Check if nested objects required`,
      `5. ❌ **Wrong connection names** - Must match EXACT node \`name\` field`,
      `6. ❌ **Inventing non-existent nodes** - Use \`search\` to verify`,
      ``,
      `---`,
      ``,
      `## ✅ Best Practices`,
      ``,
      `### Node Parameters`,
      `- ✅ Always check schema before writing`,
      `- ✅ Use exact parameter names from schema`,
      `- ❌ Never guess parameter names`,
      ``,
      `### Expressions (Modern Syntax)`,
      `- ✅ Use: \`{{ $json.fieldName }}\` (modern)`,
      `- ✅ Use: \`{{ $('NodeName').item.json.field }}\` (specific nodes)`,
      `- ❌ Avoid: \`{{ $node["Name"].json.field }}\` (legacy)`,
      ``,
      `### Node Naming`,
      `- ✅ "Action Resource" pattern (e.g., "Get Customers", "Send Email")`,
      `- ❌ Avoid generic names like "Node1", "HTTP Request"`,
      ``,
      `### Connections`,
      `- ✅ Node names must match exactly`,
      `- ✅ Structure: \`{"node": "NodeName", "type": "main", "index": 0}\``,
      ``,
      `---`,
      ``,
      `## 📚 Available Tools`,
      ``,
      `### 🔍 Unified Search (PRIMARY TOOL)`,
      `\`\`\`bash`,
      `./n8n-agent search "google sheets"`,
      `./n8n-agent search "how to use RAG"`,
      `\`\`\``,
      `**ALWAYS START HERE.** Deep search across nodes, docs, and tutorials.`,
      ``,
      `### 🛠️ Get Node Schema`,
      `\`\`\`bash`,
      `./n8n-agent get googleSheets  # Complete info`,
      `./n8n-agent schema googleSheets  # Quick reference`,
      `\`\`\``,
      ``,
      `### 🌐 Community Workflows`,
      `\`\`\`bash`,
      `./n8n-agent workflows search "slack notification"`,
      `./n8n-agent workflows info 916`,
      `./n8n-agent workflows install 4365`,
      `\`\`\``,
      ``,
      `### 📖 Documentation`,
      `\`\`\`bash`,
      `./n8n-agent docs "OpenAI"`,
      `./n8n-agent guides "webhook"`,
      `\`\`\``,
      ``,
      `### ✅ Validate`,
      `\`\`\`bash`,
      `./n8n-agent validate workflow.json`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## 🔑 Your Responsibilities`,
      ``,
      `**#1**: Use \`./n8n-agent\` tools to prevent hallucinations`,
      `**#2**: Follow the exact schema - no assumptions, no guessing`,
      `**#3**: Create workflows that work on the first try`,
      ``,
      `**When in doubt**: \`./n8n-agent get <nodeName>\``
    ].join('\n');
  }

  private getCursorRulesContent(): string {
    return [
      `# n8n-as-code rules`,
      `- Refer to AGENTS.md for complete n8n workflow standards.`,
      `- MANDATORY: Use 'n8n-agent' tools before creating/editing nodes.`,
      `- REQUIRED: Use FULL node types (e.g., 'n8n-nodes-base.switch') and LATEST typeVersion.`,
      `- Search: './n8n-agent search <query>' - Find nodes & docs (PRIMARY TOOL)`,
      `- Get: './n8n-agent get <nodeName>' - Complete node info`,
      `- Schema: './n8n-agent schema <nodeName>' - Quick parameters reference`,
      `- Docs: './n8n-agent docs <title>' - Read a specific documentation page`,
      `- Guides: './n8n-agent guides <query>' - Find tutorials and examples`,
      `- Workflows: './n8n-agent workflows search <query>' - Find community workflows (7000+)`,
      `- Related: './n8n-agent related <nodeName>' - Discover ecosystem and related nodes`,
      `- Validate: './n8n-agent validate workflow.json' - Check your workflow for errors`
    ].join('\n');
  }

  private getClineRulesContent(): string {
    return [
      `n8n_engineer_role:`,
      `  description: Expert in n8n-as-code`,
      `  instructions:`,
      `    - Read AGENTS.md for core principles.`,
      `    - MANDATORY: Use FULL node types (e.g., 'n8n-nodes-base.switch') and LATEST typeVersion.`,
      `    - Use './n8n-agent search' as your primary research tool.`,
      `    - Use './n8n-agent workflows search' to find community examples (7000+ workflows).`,
      `    - Use './n8n-agent get' to fetch exact schema before editing workflow JSON.`,
      `    - Use './n8n-agent validate workflow.json' to verify your work.`,
      `    - Ensure connections are correctly indexed.`
    ].join('\n');
  }

  private getWindsurfRulesContent(): string {
    return [
      `### n8n Development Rules`,
      `- Follow the Research Protocol in AGENTS.md.`,
      `- Tooling: Use './n8n-agent' to fetch node schemas and documentation.`,
    ].join('\n');
  }

  private getCommonRulesContent(): string {
    return [
      `# Common Rules for All AI Agents (Claude, Mistral, etc.)`,
      `- Role: Expert n8n Automation Engineer.`,
      `- Workflow Source of Truth: './n8n-agent' tools.`,
      `- Documentation: Read AGENTS.md for full syntax rules.`
    ].join('\n');
  }
}
